### PR TITLE
[nemo-qml-plugin-calendar] Propagate mKCal::Notebook::Ptr API removal.

### PR DESCRIPTION
**Pull request by dcaliste**
@pvuorela, this is a first attempt to see the changes after ::Ptr removal from mKCal. It's compiling, but I haven't run tests yet. But it gives an idea of the changes.

### CODE REVIEW

**Comment by pvuorela** [comment]
Looks like the tools/icalconverter is still having Notebook::Ptr, thus failing to build.

**Comment by pvuorela** [comment]
Looks like the tools/icalconverter is still having Notebook::Ptr, thus failing to build.

**Comment by pvuorela** [comment]
And on jolla-calendar there's the synchelper.

**Comment by pvuorela** [comment]
And on jolla-calendar there's the synchelper.

**Comment by dcaliste** [comment]
Ah, I forgot to `make clean` before building. It should be corrected now.

**Review by pvuorela — APPROVED** [review]

**Pull request closed without merging**
